services:
  - type: web
    name: nvx
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lovelysite.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"